// src/components/HoganSelection.tsx
import { Selection } from '../types';

interface HoganSelectionProps {
  selection: Selection;
  gridSize?: number;
}

export function HoganSelection({ selection, gridSize = 20 }: HoganSelectionProps) {
  const x = selection.x1 <= selection.x2 ? selection.x1 : selection.x2;
  const y = selection.y1 <= selection.y2 ? selection.y1 : selection.y2;
  const w = Math.abs(selection.x1 - selection.x2) + 1;
  const h = Math.abs(selection.y1 - selection.y2) + 1;

  return (
    <rect
      x={x * gridSize + 0.5}
      y={y * gridSize + 0.5}
      width={w * gridSize}
      height={h * gridSize}
      className="selection"
    />
  );
}

// src/components/HoganSelection.vue
<template>
  <rect
    :x="selectionScreen.x"
    :y="selectionScreen.y"
    :height="selectionScreen.h"
    :width="selectionScreen.w"
    class="selection"
  ></rect>
</template>

<script lang="ts">
const gridSize = 20;

export default {
  props: ["selection"],
  computed: {
    selectionWidth() {
      return {
        x:
          this.selection.x1 <= this.selection.x2
            ? this.selection.x1
            : this.selection.x2,
        y:
          this.selection.y1 <= this.selection.y2
            ? this.selection.y1
            : this.selection.y2,
        w: Math.abs(this.selection.x1 - this.selection.x2) + 1,
        h: Math.abs(this.selection.y1 - this.selection.y2) + 1
      };
    },
    selectionScreen() {
      return {
        x: this.selectionWidth.x * gridSize,
        y: this.selectionWidth.y * gridSize,
        w: this.selectionWidth.w * gridSize,
        h: this.selectionWidth.h * gridSize
      };
    }
  }
}
</script>

<style>
</style>
