// src/components/HoganGrid.vue
<template>
  <g>
    <line v-for="(line, index) in vlines" :key="index" :x1="line" :y1="0" :x2="line" :y2="height"></line>
    <line v-for="(line, index) in hlines" :key="index" :x1="0" :y1="line" :x2="width" :y2="line"></line>
  </g>
</template>

<script lang="ts">
import { range } from "../utils"

export default {
  props: ["width", "height"],
  computed: {
    vlines() {
      return range(this.width / 20).map(i => i * 20 + 0.5);
    },
    hlines() {
      return range(this.height / 20).map(i => i * 20 + 0.5);
    }
  }
}
</script>

// src/components/HoganGrid.tsx
import { range } from '../utils';

interface HoganGridProps {
  width: number;
  height: number;
}

export default function HoganGrid({ width, height }: HoganGridProps) {
  const vlines = range(width / 20).map(i => i * 20 + 0.5);
  const hlines = range(height / 20).map(i => i * 20 + 0.5);

  return (
    <g>
      {vlines.map((line, index) => (
        <line
          key={`v-${index}`}
          x1={line}
          y1={0}
          x2={line}
          y2={height}
        />
      ))}
      {hlines.map((line, index) => (
        <line
          key={`h-${index}`}
          x1={0}
          y1={line}
          x2={width}
          y2={line}
        />
      ))}
    </g>
  );
}
